### PR TITLE
Fix: 726 changepassword cypress fix + firebase emulator

### LINKED ISSUE #726: Fix changepassword.cy.ts Cypress test
Currently `changepassword.cy.ts` is skipped due to it's flaky nature in the pipeline. 

Expectations
Re-enable the test and assure no flakiness

### PR DESCRIPTION
**Pull request by Alessandro100**
closes #726 
**Summary:**

Fixes the changepassword cypress test and assures no flakyness
Added firebase emulator

**Expected behavior:** 

All cypress tests should pass all the time

**Testing tips:**

Run the cypress tests
`yarn run firebase:auth:emulator:dev`
[new terminal] `yarn run cypress:run` 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [X] Add or update any needed documentation to the repo
- [X] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [X] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: web-app/src/app/screens/FeedSubmission/index.tsx [hunk 1]
```diff
@@ -111,7 +111,8 @@ function Component(): React.ReactElement {
 
 export default function Home(): React.ReactElement {
   const { config } = useRemoteConfig();
-  if (config.enableFeedSubmissionStepper) {
+  // eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
+  if (config.enableFeedSubmissionStepper || !!window.Cypress) {
```
Comment (davidgamez) [inline web-app/src/app/screens/FeedSubmission/index.tsx:115]: I would avoid references to the Cypress window in production code as much as possible.

File: web-app/src/firebase.ts [hunk 2]
```diff
@@ -1,5 +1,11 @@
 import firebase from 'firebase/compat/app';
 import 'firebase/compat/remote-config';
+import 'firebase/compat/auth'; 
+
+// Cypress does not support environment variables in the same way as React
+if(window.Cypress) {
+  Object.assign(process.env, {...process.env, ...Cypress.env()})
+}
```
Comment (davidgamez) [inline web-app/src/firebase.ts:8]: Similar to code before, Cypress code can affect production behavior.

**Review by davidgamez — APPROVED** [review]
LGTM
