### PR TITLE
fix: HTTP 503 response for gbfs_feeds endpoint

### LINKED ISSUE #1182: HTTP 503 response for gbfs_feeds endpoint
### Describe the bug

The `gbfs_feeds` endpoint returns a 503 response with memory limit reached in the logs.

Image

### Steps/Code to Reproduce

- Use the following curl command, replacing the token
```
curl --request GET \
  --url https://api.mobilitydatabase.org/v1/gbfs_feeds \
  --header 'Authorization: Bearer <<TOKEN>>'
```

### Expected Results

API returns a valid 200 HTTP status response

### Actual Results

A 503 HTTP status response is returned.

### Screenshots

_No response_

### Files used

_No response_

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by davidgamez**
**Summary:**

The cause of the failure was the amount of information the SQL query was returning at once. This PR sets the maximum limit for pagination to 500 items. This is not considered a breaking change, as this is a new endpoint labeled as beta. Before this change, the `v1/gbfs_feeds` endpoint used the GTFS limit(2500).
This PR also enhances the query's performance, reducing the time it takes to return results. This is done by adding indexes and removing unnecessary joins.

Fixes #1182

## From our AI friend
This pull request introduces updates to enhance GBFS (General Bikeshare Feed Specification) support, optimize database queries, and ensure consistency across the API and tests. Key changes include improvements to query performance, updates to API documentation and parameters, and adjustments to test cases.

### Enhancements to GBFS Query Performance:
* [`api/src/shared/common/db_utils.py`](diffhunk://#diff-cd7096fe8a70b15d16ba8df397b069b2a5592bfbfeb7d50eac789bb90ae545b8L451-R453): Added `joinedload` options for `Feed.locations`, `Feed.externalids`, and `Feed.redirectingids` to optimize GBFS query performance.
* [`liquibase/changes/feat_1182.sql`](diffhunk://#diff-b1ed5952a0de493e5065e4553fd6607dd903f30e0f1bfd5e649a733a404ade95R1-R19): Introduced new indexes to improve query efficiency for GBFS-related tables, including `gbfsversion`, `redirectingid`, `externalid`, `officialstatushistory`, and `gbfsendpoint`.
* [`liquibase/changelog.xml`](diffhunk://#diff-7e45972ef13feedca4a0012017eafe7dd6db943119867eb8bca15a4ea5aa6a41R63): Included the new SQL script `feat_1182.sql` in the database changelog.

### API Documentation and Parameter Updates:
* [`docs/DatabaseCatalogAPI.yaml`](diffhunk://#diff-5c03d3e6cdf1372d1fcf8d8f052a511df313c60e8adf41d8b38aecb79f3500ecL149-R149): Replaced the `limit_query_param_gtfs_feeds_endpoint` reference with `limit_query_param_gbfs_feeds_endpoint` and added a new parameter definition for GBFS feeds with a maximum limit of 500. [[1]](diffhunk://#diff-5c03d3e6cdf1372d1fcf8d8f052a511df313c60e8adf41d8b38aecb79f3500ecL149-R149) [[2]](diffhunk://#diff-5c03d3e6cdf1372d1fcf8d8f052a511df313c60e8adf41d8b38aecb79f3500ecR1348-R1359)
* [`web-app/src/app/services/feeds/types.ts`](diffhunk://#diff-822cd1c80e61b63cc5dfca9d07730717597358e5e9e14cd8b64fd809bd997821R715-R716): Updated TypeScript types to reflect the new `limit_query_param_gbfs_feeds_endpoint` parameter for GBFS feeds. [[1]](diffhunk://#diff-822cd1c80e61b63cc5dfca9d07730717597358e5e9e14cd8b64fd809bd997821R715-R716) [[2]](diffhunk://#diff-822cd1c80e61b63cc5dfca9d07730717597358e5e9e14cd8b64fd809bd997821L851-R853)

### Test Case Adjustments:
* `api/tests/integration/test_feeds_api.py`: 
  * Added a new test case for the `/v1/gbfs_feeds` endpoint with a hard limit of 500.
  * Updated the `test_hard_limits` assertion to expect a `422` status code instead of a non-`200` status code.

### Minor Fixes:
* [`api/src/shared/database/database.py`](diffhunk://#diff-21663f6b58fec00f23290aa025d6b73e4d1733eab8f342c1155a39fe466cc4acL127-R127): Corrected the logging level comparison in the `with_db_session` decorator to use `logging.getLevelName`.

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

**Testing tips:**

Provide tips, procedures and sample files on how to test the feature.
Testers are invited to follow the tips AND to try anything they deem relevant outside the bounds of the testing tips. 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ ] Add or update any needed documentation to the repo
- [ ] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: liquibase/changes/feat_1182.sql [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+CREATE INDEX IF NOT EXISTS idx_redirectingid_source_id
+  ON redirectingid (source_id);
+
+CREATE INDEX IF NOT EXISTS idx_redirectingid_target_id
+  ON redirectingid (target_id);
+
+CREATE INDEX IF NOT EXISTS idx_externalid_feed_id
+  ON externalid (feed_id);
+
+CREATE INDEX IF NOT EXISTS idx_officialstatushistory_feed_id
```
Comment (davidgamez) [inline liquibase/changes/feat_1182.sql:15]: The officialstatushistory table was removed from the GBFS query. However, this index benefits other queries that use it, such as GTFS and GTFS-RT.

**Review by cka-y — APPROVED** [review]
LGTM
