### PR TITLE
fix: curl command and preview fixes

### LINKED ISSUE #176: curl command and preview fixes on https://mobilitydatabase.org/account
- API test curl command text should always point to prod, not be a variable. Right now it's relative to environment. Command itself points to prod when copied, but the text previewed does not:
Screenshot 2023-11-25 at 1 28 50 PM

- In black text, don’t include full token, have [your access token] instead written as a string, like it is before the access token is generated. The real access token should be copied for the user, but not displayed in the black text.

Screenshot 2023-11-25 at 1 29 59 PM

### PR DESCRIPTION
**Pull request by cka-y**
**Summary:**
Closes #176 
Changed the curl command to point to the PROD endpoint and disabled the display of the token within the API test block

**Testing tips:**
Login to your account and generate an access token -- the token should not be displayed in the `API Test` box but will be properly copied to your clipboard. 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: web-app/src/app/screens/Account.tsx [hunk 1]
```diff
@@ -588,18 +589,15 @@ export default function APIAccount(): React.ReactElement {
...
               <br />
               <span style={{ color: '#f1fa8c' }}>--header</span> &apos;Accept:
               application/json&apos;
               <span style={{ color: '#f1fa8c' }}>\</span>
               <br />
               <span style={{ color: '#f1fa8c' }}>--header</span>
-              &apos;Authorization: Bearer{' '}
-              {user?.accessToken ?? '[Your Access Token]'}
-              &apos;
+              &apos;Authorization: Bearer [Your Access Token] &apos;
```
Comment (cka-y) [inline web-app/src/app/screens/Account.tsx:600]:
```suggestion
              &apos;Authorization: Bearer [Your Access Token]&apos;
```

**Review by davidgamez — APPROVED** [review]
LGTM!
