### PR TITLE
fix: 1396 search endpoint returning uid as id instead of stable id for latest dataset an redirects

### LINKED ISSUE #1396: Search endpoint returning UID as ID instead of stable_id for latest dataset an redirects
### Describe the bug

Using the search endpoint, the ID of the latest dataset is the UID, not the stable ID (double checked with Metabase). When using other endpoints, I get the stable ID.

### Steps/Code to Reproduce

Use the following curl command, replacing the token with a valid token:
```
curl --request GET \
  --url 'https://api.mobilitydatabase.org/v1/search?limit=15&data_type=gtfs' \
  --header 'Authorization: Bearer TOKEN'
```
### Expected Results

Stable IDs should be returned in all ID fields.

### Actual Results

The IDs are shown as UID in the following field
- Latest dataset id
- redirect target and source ID
- external ids

### Screenshots

_No response_

### Files used

_No response_

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by qcdyx**
**Summary:**

Closes #1396 

**Expected behavior:** 
latest_dataset_id and redirect_ids's target_id should be displayed as stable_id, not unique id.
image

image

**Testing tips:**

Provide tips, procedures and sample files on how to test the feature.
Testers are invited to follow the tips AND to try anything they deem relevant outside the bounds of the testing tips. 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [ ] Add or update any needed documentation to the repo
- [ ] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

File: liquibase/changes/feat_1396.sql [hunk 1]
```diff
@@ -0,0 +1,254 @@
+-- Latest dataset id should return the feed_id, not the UID of the dataset
+
+DROP MATERIALIZED VIEW IF EXISTS feedsearch;
+
+ALTER TABLE feed
+ALTER COLUMN note TYPE TEXT;
```
Comment (davidgamez) [inline liquibase/changes/feat_1396.sql]: Please remove this change that is already in a different Liquibase changeset.

```suggestion
```
